;;; org-version.el --- autogenerated file, do not edit
;;
;;; Code:
;;;###autoload
(defun org-release ()
  "The release version of org-mode.
  Inserted by installing org-mode or when a release is made."
   (let ((org-release "7.8.11"))
     org-release))
;;;###autoload
(defun org-git-version ()
  "The Git version of org-mode.
  Inserted by installing org-mode or when a release is made."
   (let ((org-git-version "release_7.8.11-507-g8ab1d7"))
     org-git-version))
;;;###autoload
(defconst org-odt-data-dir "/usr/share/emacs/etc/org"
  "The location of ODT styles.")

(provide 'org-version)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; coding: utf-8
;; End:
;;; org-version.el ends here
